apiVersion: v1
kind: Service
metadata:
  name: sad-leela-97941162a0-srv
  namespace: apps-prod
spec:
  selector:
    app: sad-leela-97941162a0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP